### ISSUE TITLE
bilibili弹幕列表自动播放实时滚动脚本失效

### ISSUE THREAD

**Issue by TomIsFat** [YuJiZhao/script#1]
经过简单的测试，以下段落成功运行：
// 发起请求，拿到弹幕数据
// 存储数据
// 执行排序
// 修改弹幕列表
其他函数均未被执行

**Comment by YuJiZhao** [comment]
脚本是很早以前写的，随着B站的不断更新，现已失效，脚本暂无维护更新计划
